apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: jx-staging
type: Opaque
data:
  secret: WXprNFlXVXpZemcwTURRM05qZGhZams1TWpVMk1EWm1ObVJpTVdGaU9URmtaamcwTldNNFl6QXpNV1UxTm1JeU9UUmtObVF5TVRVeE1UZG1PV1kxTTJJNE1EUTNObVF3T0RFNE4ySTJabVZqWlRnNU56UTBaREl4TXpGa1ltVXpNamN4WlE9PQ==
