apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: store-gw-virtualservice
  labels:
    service: store-gw-virtualservice
spec:
  hosts:
    - store.jx-staging.cluster12.tagscloud.org
  gateways:
    - knative-serving/cluster-local-gateway
    - knative-serving/knative-ingress-gateway  
  http:
    - match:
        - uri:
            prefix: /services/invoice/
      rewrite:
        authority: invoice.jx-staging.cluster12.tagscloud.org
        uri: /
      route:
        - destination:
            host: istio-ingressgateway.istio-system.svc.cluster.local
            port:
              number: 80
    - match:
        - uri:
            prefix: /services/notification/
      rewrite:
        authority: notification.jx-staging.cluster12.tagscloud.org
        uri: /
      route:
        - destination:
            host: istio-ingressgateway.istio-system.svc.cluster.local
            port:
              number: 80
    - match:
        - uri:
            prefix: /services/product/
      rewrite:
        authority: product.jx-staging.cluster12.tagscloud.org
        uri: /
      route:
        - destination:
            host: istio-ingressgateway.istio-system.svc.cluster.local
            port:
              number: 80
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: istio-ingressgateway.istio-system.svc.cluster.local
            port:
              number: 80
